module.exports = [
  {
    question: "Question 1",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 2",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 3",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 4",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 5",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 6",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 7",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 8",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 9",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 10",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 11",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 12",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 13",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 14",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 15",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 16",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 17",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 18",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 19",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 20",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 21",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 22",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 23",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 24",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 25",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 26",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 27",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 28",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 29",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 30",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 31",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 32",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 33",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 34",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 35",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 36",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 37",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 38",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 39",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 40",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 41",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 42",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 43",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 44",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 45",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 46",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 47",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 48",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 49",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 50",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 51",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 52",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 53",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 54",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 55",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 56",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 57",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 58",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 59",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 60",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 61",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 62",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 63",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 64",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 65",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 66",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 67",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 68",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 69",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 70",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 71",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 72",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 73",
    subject: "SubjectA",
    topic: "TopicY",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 74",
    subject: "SubjectA",
    topic: "TopicZ",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 75",
    subject: "SubjectA",
    topic: "TopicX",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 76",
    subject: "SubjectB",
    topic: "TopicQ",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 77",
    subject: "SubjectB",
    topic: "TopicR",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 78",
    subject: "SubjectB",
    topic: "TopicP",
    difficulty: "hard",
    marks: 5,
  },

  {
    question: "Question 79",
    subject: "SubjectB",
    topic: "TopicN",
    difficulty: "easy",
    marks: 1,
  },
  {
    question: "Question 80",
    subject: "SubjectB",
    topic: "TopicO",
    difficulty: "medium",
    marks: 2,
  },
  {
    question: "Question 81",
    subject: "SubjectB",
    topic: "TopicM",
    difficulty: "hard",
    marks: 5,
  },
];
